-- Run in Supabase SQL editor to store student document metadata.
-- Files are stored in the students_avatars bucket under {studentId}/documents/.

CREATE TABLE IF NOT EXISTS student_document (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student bigint NOT NULL REFERENCES students (id) ON DELETE CASCADE,
  file_name text NOT NULL,
  storage_path text NOT NULL,
  file_url text NOT NULL,
  mime_type text,
  file_size bigint,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS student_document_student_id_idx
  ON student_document (student);
