-- Run in Supabase SQL editor to create tuition tables linked to students.
-- class_credits may go negative; payments add credits back via tuition_transaction.

CREATE TABLE IF NOT EXISTS tuition (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student bigint NOT NULL UNIQUE REFERENCES students (id) ON DELETE CASCADE,
  class_credits numeric NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tuition_transaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student bigint NOT NULL REFERENCES students (id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  transaction_type text NOT NULL CHECK (
    transaction_type IN ('attendance', 'payment', 'adjustment')
  ),
  session bigint REFERENCES session (id) ON DELETE SET NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tuition_transaction_student_id_idx
  ON tuition_transaction (student);

CREATE INDEX IF NOT EXISTS tuition_transaction_session_id_idx
  ON tuition_transaction (session);
